// src/app/App.tsx
import { useState } from 'react';
import { Sidebar } from './components/Sidebar';
import { Header } from './components/Header';
import { MainContent } from './components/MainContent';
import { Login } from './components/Login';
import { ForgotPassword } from './components/ForgotPassword';
import { SignUp } from './components/SignUp';
import { Home } from './components/pages/Home';
import { Dashboard } from './components/pages/Dashboard';
import { Documents } from './components/pages/Documents';
import { Users } from './components/pages/Users';
import { Settings } from './components/pages/Settings';

export default function App() {
  const [sidebarOpen, setSidebarOpen] = useState(true);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [currentPage, setCurrentPage] = useState('home');
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [authView, setAuthView] = useState<'login' | 'forgotPassword' | 'signUp'>('login');

  const toggleSidebar = () => {
    setSidebarOpen(!sidebarOpen);
  };

  const handleLogin = () => {
    setIsLoggedIn(true);
    setAuthView('login');
  };

  const handleLogout = () => {
    setIsLoggedIn(false);
    setCurrentPage('home');
    setDrawerOpen(false);
    setAuthView('login');
  };

  const handlePageChange = (page: string) => {
    setCurrentPage(page);
  };

  // ログインしていない場合は認証画面を表示
  if (!isLoggedIn) {
    if (authView === 'forgotPassword') {
      return <ForgotPassword onBack={() => setAuthView('login')} />;
    }
    if (authView === 'signUp') {
      return <SignUp onBack={() => setAuthView('login')} onSignUpSuccess={handleLogin} />;
    }
    return <Login onLogin={handleLogin} onForgotPassword={() => setAuthView('forgotPassword')} onSignUp={() => setAuthView('signUp')} />;
  }

  // ページコンテンツを選択
  const renderPage = () => {
    switch (currentPage) {
      case 'home':
        return <Home />;
      case 'dashboard':
        return <Dashboard />;
      case 'documents':
        return <Documents />;
      case 'users':
        return <Users />;
      case 'settings':
        return <Settings />;
      default:
        return <Home />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-50">
      {/* サイドバー */}
      <Sidebar 
        isOpen={sidebarOpen} 
        onToggle={toggleSidebar} 
        onPageChange={handlePageChange} 
        currentPage={currentPage}
        drawerOpen={drawerOpen}
        onDrawerToggle={() => setDrawerOpen(!drawerOpen)}
        onLogout={handleLogout}
      />

      {/* メインコンテンツエリア */}
      <div
        className={`transition-all duration-300 ${
          sidebarOpen ? 'lg:ml-64' : 'ml-0'
        }`}
      >
        {/* ヘッダー */}
        <Header onMenuClick={toggleSidebar} sidebarOpen={sidebarOpen} />

        {/* ボディ部 */}
        {renderPage()}
      </div>
    </div>
  );
}

// src/App.vue
<template>
  <div class="min-h-screen bg-slate-50">
    <template v-if="!isLoggedIn">
      <div class="min-h-screen flex items-center justify-center">
        <Login v-if="authView === 'login'" @login="handleLogin" @forgot="showForgot" @signup="showSignup" />
        <ForgotPassword v-else-if="authView === 'forgotPassword'" @back="showLogin" />
        <SignUp v-else-if="authView === 'signUp'" @back="showLogin" @signup-success="handleLogin" />
      </div>
    </template>

    <template v-else>
      <Sidebar
        :is-open="sidebarOpen"
        @toggle="toggleSidebar"
        @page-change="handlePageChange"
        :current-page="currentPage"
        :drawer-open="drawerOpen"
        @drawer-toggle="drawerOpen = !drawerOpen"
        @logout="handleLogout"
      />

      <div :class="['transition-all duration-300', sidebarOpen ? 'lg:ml-64' : 'ml-0']">
        <Header @menu-click="toggleSidebar" :sidebar-open="sidebarOpen" />
        <component
          :is="currentView"
          @signup-success="handleLogin"
          @back="showLogin"
        />
      </div>
    </template>
  </div>
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import Sidebar from './components/Sidebar.vue'
import Header from './components/Header.vue'
import Login from './components/Login.vue'
import ForgotPassword from './components/ForgotPassword.vue'
import SignUp from './components/SignUp.vue'
import Home from './components/pages/Home.vue'
import Dashboard from './components/pages/Dashboard.vue'
import Documents from './components/pages/Documents.vue'
import Users from './components/pages/Users.vue'
import Settings from './components/pages/Settings.vue'

const sidebarOpen = ref(true)
const isLoggedIn = ref(false)
const currentPage = ref('home')
const drawerOpen = ref(false)
const authView = ref<'login' | 'forgotPassword' | 'signUp'>('login')

const toggleSidebar = () => { sidebarOpen.value = !sidebarOpen.value }
const handleLogin = () => { isLoggedIn.value = true; authView.value = 'login' }
const handleLogout = () => {
  isLoggedIn.value = false
  currentPage.value = 'home'
  drawerOpen.value = false
  authView.value = 'login'
}
const handlePageChange = (page: string) => { currentPage.value = page }

function showForgot(){ authView.value = 'forgotPassword' }
function showSignup(){ authView.value = 'signUp' }
function showLogin(){ authView.value = 'login' }

const currentView = computed(() => {
  if (!isLoggedIn.value) {
    if (authView.value === 'forgotPassword') return ForgotPassword
    if (authView.value === 'signUp') return SignUp
    return Login
  }

  switch (currentPage.value) {
    case 'home': return Home
    case 'dashboard': return Dashboard
    case 'documents': return Documents
    case 'users': return Users
    case 'settings': return Settings
    default: return Home
  }
})
</script>

<style>
/* local styles if needed */
</style>
